### ISSUE TITLE
Looks like update is needed to match the changes in neorg code.

### ISSUE THREAD

**Issue by snuffop** [max397574/neorg-kanban#3]
I've noticed this in other modules a bit back when neorg was updated to 5.0.0  though you may want to know

 1 .../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:438
    2 Unable to load module external.kanban - ...eorg-kanban/lua/neorg/modules/external/kanban/module.lua:1: module 'neorg.modules.base' not found:
    3 >   no field package.preload['neorg.modules.base']
    4 cache_loader: module neorg.modules.base not found
    5 cache_loader_lib: module neorg.modules.base not found
    6 >   no file './neorg/modules/base.lua'
    7 >   no file '/usr/share/luajit-2.1/neorg/modules/base.lua'
    8 >   no file '/usr/local/share/lua/5.1/neorg/modules/base.lua'
    9 >   no file '/usr/local/share/lua/5.1/neorg/modules/base/init.lua'
   10 >   no file '/usr/share/lua/5.1/neorg/modules/base.lua'
   11 >   no file '/usr/share/lua/5.1/neorg/modules/base/init.lua'
   12 >   no file './neorg/modules/base.so'
   13 >   no file '/usr/local/lib/lua/5.1/neorg/modules/base.so'
   14 >   no file '/usr/lib/lua/5.1/neorg/modules/base.so'
   15 >   no file '/usr/local/lib/lua/5.1/loadall.so'
   16 >   no file './neorg.so'

I will look into this later and learn lua and maybe have a PR

**Comment by max397574** [comment]
this module no longer works anyway atm because it was based on the now deleted gtd system
